server:
  port: 8100
spring:
  application:
    name: cambio-service
  datasource:
    url: jdbc:postgresql://localhost/cambio_db
    username: postgres
    password: 
  jpa:
   hibernate:
      ddl-auto: none
   show-sql: true
   properties:
     hibernate:
       format_sql: true
  flyway:
    locations:
    - classpath:/db_migration

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  
  endpoint:
    health:
      show-details: always