server:
  port: 8000
spring:
  application:
    name: produto-service
  datasource:
    url: jdbc:postgresql://localhost/produto_db
    username: postgres
    password: 
  jpa:
   hibernate:
      ddl-auto: none
   show-sql: true
   properties:
     hibernate:
       format_sql: true

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  
  endpoint:
    health:
      show-details: always